services:
  postgres-db:
    image: postgres:16-alpine
    container_name: umarket_postgres
    environment:
      POSTGRES_DB: U-Market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15262005
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: umarket_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@umarket.com
      PGADMIN_DEFAULT_PASSWORD: 15262005
    ports:
      - "8080:80"
    restart: always

  rabbitmq:
    image: rabbitmq:4-management
    container_name: umarket_rabbitmq
    ports:
      - "5672:5672"   # AMQP: lo usa el backend
      - "15672:15672" # Panel de gestión: http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: umarket
      RABBITMQ_DEFAULT_PASS: umarket123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: umarket_backend
    ports:
      - "8081:8080" # El backend se expone en el puerto 8081 porque se uso  el puerto 8080 para pgAdmin
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/U-Market
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 15262005
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: umarket
      RABBITMQ_PASSWORD: umarket123
    depends_on:
      - postgres-db
      - rabbitmq
    restart: unless-stopped

volumes:
  pgdata:
  rabbitmq_data: