spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/U-Market
    username: postgres
    password: 15262005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true